export enum graphTypes {
    SALES_REVENUE = 'SALES_REVENUE',
    ITEMS_SOLD = 'ITEMS_SOLD',
    ORDERS_PLACED = 'ORDERS_PLACED',
    NUMBER_OF_SHIPMENTS = 'NUMBER_OF_SHIPMENTS',
    NUMBER_OF_VISITORS = 'NUMBER_OF_VISITORS',
};
